services:
  db:
    container_name: homework_help_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
        - 5132:5432
    networks:
      - homework-network
    restart: unless-stopped

networks:
   homework-network:
        driver: bridge
volumes:
    db: