name: notevault-hub
services:
  database:
    container_name: homework_help_db
    image: postgres:16.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: homework_help
      PGDATA: /data/postgres
    volumes:
      - db_vol:/data/postgres
    expose:
      - 5432
    restart: unless-stopped

  backend:
    image: "notevault_backend:latest"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - USER_NAME=${USER_NAME}
      - USER_PASSWORD=${USER_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - RESEND_FROM=${RESEND_FROM}
      - RESEND_API_KEY=${RESEND_API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - database
      - cache
    restart: unless-stopped
  cache:
    image: "redis:7-alpine"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_vol:/data
    restart: unless-stopped

volumes:
  db_vol:
  redis_vol:

