server:
  port: 8888
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5132/homework_help
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  main:
    banner-mode: off
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

  sql:
    init:
      mode: always
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1 hour
  data:
    redis:
      host: localhost
      port: 6379

application:
  security:
    jwt:
      #should be loaded from env
      secret-key: 414E635266556A586E3272357538772F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days